# ==================================
# Avoiding Experiment Configuration
# ==================================

target_values: # Global target values used across all phases unless overridden in a phase
  distances: [ 30, 41.7, 53.3, 65, 76.7, 88.3, 100 ]   # Default distances (%)
  intensities: [28, 40, 52, 64, 76, 88, 100] #reverse of distance if mapping is reversed

# ==================
# Mapping Subgroups
# ==================
# Each subgroup defines a mapping type and its associated trial phases
subgroups:

  # ---- Direct Mapping ----
  direct:
    mapping_type: "direct" # Direct: greater distance → higher intensity

    # Ordered list of experiment phases in this mapping group
    phases:
      - name: "Pre-Test" # Phase name shown in trial metadata
        task: "reaching" # Task type: "reaching" or "avoiding"
        blocks: 1        # Number of blocks in this phase
        repetitions: 8   # Number of repetitions per target
        # Optional: override default target values (not used here)

      - name: "Pre-Test"
        task: "avoiding"
        blocks: 1
        repetitions: 8

      - name: "Training"
        task: "avoiding"
        blocks: 5
        # Overriding default target and intensity values for the training phase
        target_distances: [ 41.7, 65, 88.3, 100 ]
        intensity_levels: [28, 52, 76, 100]
        repetitions: 10

      - name: "Post-Test"
        task: "avoiding"
        blocks: 1
        repetitions: 8

      - name: "Training"
        task: "avoiding"
        blocks: 1
        target_distances: [ 41.7, 65, 88.3, 100 ]
        intensity_levels: [28, 52, 76, 100]
        repetitions: 10

      - name: "Post-Test"
        task: "reaching"
        blocks: 1
        repetitions: 8

  # ---- Reversed Mapping ----
  reversed:
    mapping_type: "reversed" # Reversed: greater distance → lower intensity

    # Ordered list of experiment phases in this mapping group
    phases:
      - name: "Pre-Test"
        task: "reaching"
        blocks: 1
        repetitions: 8

      - name: "Pre-Test"
        task: "avoiding"
        blocks: 1
        repetitions: 8

      - name: "Training"
        task: "avoiding"
        blocks: 5
        # Overriding default target and intensity values for the training phase
        target_distances: [ 41.7, 65, 88.3, 100 ]
        intensity_levels: [100, 76, 52, 28] #Reversed
        repetitions: 10

      - name: "Post-Test"
        task: "avoiding"
        blocks: 1
        repetitions: 8

      - name: "Training"
        task: "avoiding"
        blocks: 1
        target_distances: [ 41.7, 65, 88.3, 100 ]
        intensity_levels: [100, 76, 52, 28] #Reversed
        repetitions: 10

      - name: "Post-Test"
        task: "reaching"
        blocks: 1
        repetitions: 8
